name: release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Sanity Check
        run: |
          cat /proc/cpuinfo

      - name: Setup Rust
        uses: ./.github/actions/setup-rust
        with:
          caller-workflow-name: test

      - name: Clippy check
        run: cargo clippy --all-features --all-targets --tests -- -D warnings

      - name: Build
        run: cargo build --release

      - name: Copy artifact from container
        run: |
          cp target/release/jito-shredstream-proxy ./jito-shredstream-proxy-x86_64-unknown-linux-gnu
          ls -lh .
          file ./jito-shredstream-proxy-x86_64-unknown-linux-gnu

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ./jito-shredstream-proxy-x86_64-unknown-linux-gnu
